//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hcPeopleSearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public int peopleID { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public System.DateTime dob { get; set; }
        public Nullable<int> age { get; set; }
        public string interests { get; set; }
        public string soundex_first_name { get; set; }
        public string soundex_last_name { get; set; }
    }
}
